### ISSUE TITLE
Group replication seeds & Group replication credentials

### ISSUE THREAD

**Issue by dionmes** [gites/k8s-mysql-group-replication#6]
Hi,
Love this POC, and it helped me a lot in getting group replication working on Kubernetes.

I have one tip which works for me. By adding the replication port to the service you can populate **loose-group_replication_group_seeds** with the service name, instead of adding instances to the setting. This prevents DNS look ups for non existing instances and all the instances can than be seeds for the group replication without manually adding them.

The other thing is, I ran into this with Docker and now also with Kubernetes. The Group replication credentials don't have to be added to the extra instances, however all the tutorials and documentation on MySQL say that you have to. Looking at your scripts you also don't create the replication user, where did you get that info? Should we request changing the documentation on MySQL ? Put this question also on StackOverflow [https://stackoverflow.com/questions/48620247/group-replication-recovery-credentials-already-exists](url)

**Comment by gites** [comment]
Hi,

I'm glad that I could help :).

Setting **loose-group_replication_group_seeds** to service name, didn't work for me. First pod is starting ok, but second one failed with:
```
2018-02-21T18:03:21.176251Z 0 [Note] Plugin group_replication reported: 'connecting to mysql-rw.mysql-test 24901'                                                                                                 
2018-02-21T18:03:21.177824Z 0 [Note] Plugin group_replication reported: 'client connected to mysql-rw.mysql-test 24901 fd 61'
2018-02-21T18:03:21.178272Z 0 [Note] Plugin group_replication reported: 'cli_err 2'                                     
2018-02-21T18:03:22.178642Z 0 [Note] Plugin group_replication reported: 'cli_err 2'  
```

Anyway, isn't service load-balanced between pods? So instead of hitting **mysql-1:24901** request can by sent to **mysql-0:24901**? Can you share some examples?

About credentials. If you are coping **/var/lib/mysql/** from one server to another, you don't need to create replication user. It's already there within `mysql` database. AFAIK MySQL documentation refer to situation where you have 3 or more uncofigured, standalone servers and you don't copy `mysql` database between them.

**Comment by dionmes** [comment]
Isn't that error because of the report_host setting missing ? I set the report_host to the mysql server IP ("report_host=$ip") address and the (loose-)group_replication_local_address also to the IP address ($ip:24901") instead of DNS name.  

The service does load balance between pods but only replicates (data) with the replication seeds you put in loose-group_replication_group_seeds. So by using the service also for replication seeding the scaling is more balanced.

On the credentials, I connect freshly installed empty servers, no data at all. After connecting it replicates the rpm_user ?!?!?! I see it in my local docker environment and in my Kubernetes cluster. This is getting weird ....
